-- MySQL Script generated by MySQL Workbench
-- Sun Oct 20 22:15:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blog` ;

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8mb4;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`categories` ;

CREATE TABLE IF NOT EXISTS `blog`.`categories` (
  `id` INT(11) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `parentId` INT(11) NOT NULL DEFAULT '0',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`comments` ;

CREATE TABLE IF NOT EXISTS `blog`.`comments` (
  `id` INT(11) NOT NULL,
  `userId` INT(11) NOT NULL,
  `postId` INT(11) NOT NULL,
  `statusId` INT(11) NOT NULL,
  `parentId` INT(11) NOT NULL DEFAULT '0',
  `comment` VARCHAR(1000) NOT NULL,
  `likeCount` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`userId` ASC),
  INDEX `fk_comments_posts1_idx` (`postId` ASC),
  INDEX `fk_comments_enums1_idx` (`statusId` ASC),
  CONSTRAINT `fk_comments_enums1`
    FOREIGN KEY (`statusId`)
    REFERENCES `blog`.`enums` (`id`),
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `blog`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `blog`.`enums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`enums` ;

CREATE TABLE IF NOT EXISTS `blog`.`enums` (
  `id` INT(11) NOT NULL,
  `enum` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `blog`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`posts` ;

CREATE TABLE IF NOT EXISTS `blog`.`posts` (
  `id` INT(11) NOT NULL,
  `userId` INT(11) NOT NULL,
  `statusId` INT(11) NOT NULL,
  `categoryId` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `post` TEXT NOT NULL,
  `readCount` INT(11) NOT NULL,
  `likeCount` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC),
  INDEX `fk_posts_enums1_idx` (`statusId` ASC),
  INDEX `fk_posts_categories1_idx` (`categoryId` ASC),
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `blog`.`categories` (`id`),
  CONSTRAINT `fk_posts_enums1`
    FOREIGN KEY (`statusId`)
    REFERENCES `blog`.`enums` (`id`),
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `blog`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `blog`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`users` ;

CREATE TABLE IF NOT EXISTS `blog`.`users` (
  `id` INT(11) NOT NULL,
  `roleId` INT(11) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  `verified` TINYINT(4) NOT NULL DEFAULT '0',
  `subscribed` TINYINT(4) NOT NULL DEFAULT '0',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_enums1_idx` (`roleId` ASC),
  CONSTRAINT `fk_users_enums1`
    FOREIGN KEY (`roleId`)
    REFERENCES `blog`.`enums` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
